require: rubocop-performance

AllCops:
  Exclude:
    - "db/schema.rb"
  DisplayCopNames: true
Layout/AlignHash:
  Enabled: false
Layout/EmptyLines:
  Enabled: true
  Exclude:
    - "Gemfile"
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: true
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
Metrics/LineLength:
  Enabled: true
  Max:     120
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment: 
  Enabled: false
Style/StringLiterals:
  Enabled: false
